---
- hosts: all
  become: yes
  vars :
  - ansible_python_interpreter: /usr/bin/python
  tasks:
  - name: Install packages
    apt:
      name:
      - unzip
      state: latest
      cache_valid_time: 3600
